runtime: php81

automatic_scaling:
  max_instances: 20

handlers:
- url: /
  script: api/index.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve php scripts.
- url: /(.+\.php)$
  script: \1